### PR TITLE
Upgrade to BookKeeper 4.9.0

### PR DESCRIPTION
**Pull request by eolivelli**

### CODE REVIEW

**Comment by eolivelli** [comment]
@diegosalvi I will wait for Travis and then merge your commit

**Comment by eolivelli** [comment]
@diegosalvi We need to  fix #9 before merging this one.
Anyway HerdDB already has been migrated to 0.9 so this fix is to be done asap

**Comment by eolivelli** [comment]
@diegosalvi now the build is failing
[ERROR] /home/travis/build/diennea/blobit/blobit-core/src/test/java/org/blobit/core/cluster/ZKTestEnv.java:[31,34] cannot find symbol
  symbol:   class ReflectionUtils
  location: package org.apache.bookkeeper.util
[ERROR] /home/travis/build/diennea/blobit/blobit-core/src/test/java/org/blobit/core/cluster/ZKTestEnv.java:[87,39] cannot find symbol
  symbol:   variable ReflectionUtils
  location: class org.blobit.core.cluster.ZKTestEnv

**Comment by eolivelli** [comment]
@diegosalvi  this is good to go

Travis passed

**Review by diegosalvi — APPROVED** [review]

**Pull request merged**
